---
dist: bionic
sudo: false

language: python
python:
  - "3.8.5"

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip3 install pre-commit
  - pip3 install pipenv

install:
  - pipenv install --dev

# Pre-commit needs to skip vagrant-validate as its not installed
env:
  - SKIP=vagrant-validate

script:
  # Run tests
  - pre-commit run --all-files
