---
- name: "Epiphany Browser (pin)"
  become: true
  copy:
    dest: /etc/apt/preferences.d/epiphany-browser
    group: root
    mode: "u=rw,go=r"
    owner: root
    src: epiphany-browser.pin
  when: ansible_lsb.id == 'Raspbian'

- name: "Epiphany Browser: install"
  become: true
  apt:
    name: epiphany-browser
    state: present
  notify: restart LightDM

- name: "Epiphany Browser: Profile Dir"
  become: true
  file:
    group: "{{ kiosk_user }}"
    mode: "u=rwx,go="
    owner: "{{ kiosk_user }}"
    path: /home/{{ kiosk_user }}/.config/epiphany
    state: directory
  notify: restart LightDM
